import type { ProfileData } from "./types";
import { findSkill } from "@/data/skills";
import { SOCIAL_PLATFORMS } from "@/data/socials";

export function generateReadme(p: ProfileData): string {
  const out: string[] = [];
  const user = p.githubUsername.trim();

  if (p.name) {
    out.push(`<h1 align="center">Hi 👋, I'm ${p.name}</h1>`);
  }
  if (p.tagline) {
    out.push(`<h3 align="center">${p.tagline}</h3>`);
  }
  if (p.addons.visitorBadge && user) {
    out.push(
      `<p align="center"><img src="https://komarev.com/ghpvc/?username=${user}&label=Profile%20views&color=0e75b6&style=flat" alt="${user}" /></p>`
    );
  }

  const about: string[] = [];
  if (p.currentWork) {
    const link = p.currentWorkLink ? ` [${p.currentWork}](${p.currentWorkLink})` : ` **${p.currentWork}**`;
    about.push(`- 🔭 I’m currently working on${link}`);
  }
  if (p.learning) about.push(`- 🌱 I’m currently learning **${p.learning}**`);
  if (p.askMeAbout) about.push(`- 💬 Ask me about **${p.askMeAbout}**`);
  if (p.portfolio) about.push(`- 👨‍💻 Check out my work at [${stripProtocol(p.portfolio)}](${p.portfolio})`);
  if (p.blog) about.push(`- 📝 I write articles on [${stripProtocol(p.blog)}](${p.blog})`);
  if (p.email) about.push(`- 📫 How to reach me: **${p.email}**`);
  if (p.funFact) about.push(`- ⚡ Fun fact: **${p.funFact}**`);
  if (about.length) out.push(about.join("\n"));

  const socialEntries = SOCIAL_PLATFORMS.filter((s) => p.socials[s.id]?.trim());
  if (socialEntries.length) {
    const badges = socialEntries
      .map((s) => {
        const value = p.socials[s.id].trim();
        const url = `${s.urlPrefix}${value}`;
        const badge = `https://img.shields.io/badge/${encodeURIComponent(s.label.replace(/-/g, "--"))}-${s.badgeColor}?style=for-the-badge&logo=${s.badgeLogo}&logoColor=white`;
        return `<a href="${url}" target="_blank"><img src="${badge}" alt="${s.label}" /></a>`;
      })
      .join("\n");
    out.push(`<h3 align="left">Connect with me</h3>\n<p align="left">\n${badges}\n</p>`);
  }

  if (p.skills.length) {
    const icons = p.skills
      .map((id) => findSkill(id))
      .filter((s): s is NonNullable<typeof s> => Boolean(s))
      .map(
        (s) =>
          `<a href="${s.docUrl}" target="_blank" rel="noreferrer"><img src="${s.iconUrl}" alt="${s.label}" width="40" height="40" /></a>`
      )
      .join("\n");
    out.push(`<h3 align="left">Languages and Tools</h3>\n<p align="left">\n${icons}\n</p>`);
  }

  if (user) {
    if (p.addons.staticStatsWorkflow) {
      // Stats come from an SVG committed by the Actions workflow — no shared
      // third-party instance in the hot path, so nothing to rate-limit or 404.
      out.push(
        `<h3 align="left">GitHub Stats</h3>\n<p align="left"><img src="./github-metrics.svg" alt="GitHub metrics" /></p>\n\n<!-- github-metrics.svg is generated by .github/workflows/update-stats.yml (included in your download) -->`
      );
    } else {
      const theme = p.addons.statsTheme;
      const cards: string[] = [];
      if (p.addons.githubStats)
        cards.push(`<img src="https://github-readme-stats.vercel.app/api?username=${user}&show_icons=true&theme=${theme}" alt="stats" />`);
      if (p.addons.topLangs)
        cards.push(`<img src="https://github-readme-stats.vercel.app/api/top-langs?username=${user}&layout=compact&theme=${theme}" alt="top languages" />`);
      if (p.addons.streak)
        cards.push(`<img src="https://streak-stats.demolab.com/?user=${user}&theme=${theme}" alt="streak" />`);
      if (p.addons.trophies)
        cards.push(`<img src="https://github-profile-trophy.vercel.app/?username=${user}&theme=onedark" alt="trophies" />`);
      if (cards.length) out.push(`<h3 align="left">GitHub Stats</h3>\n<p align="left">\n${cards.join("\n")}\n</p>`);
    }
  }

  return out.join("\n\n") + "\n";
}

export function generateStatsWorkflow(p: ProfileData): string {
  const user = p.githubUsername.trim() || "YOUR_USERNAME";
  const plugins: string[] = [];
  if (p.addons.topLangs) {
    plugins.push("          plugin_languages: yes", '          plugin_languages_limit: 8');
  }
  if (p.addons.streak) {
    plugins.push("          plugin_isocalendar: yes");
  }
  if (p.addons.trophies) {
    plugins.push("          plugin_achievements: yes", "          plugin_achievements_threshold: B");
  }
  return `name: Update profile stats

# Renders GitHub stats to a committed SVG so the README never depends on a
# shared third-party instance (no rate limits, no dead Heroku apps).
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: \${{ secrets.GITHUB_TOKEN }}
          user: ${user}
          filename: github-metrics.svg
          base: header, activity, community, repositories
${plugins.join("\n")}
`;
}

function stripProtocol(url: string) {
  return url.replace(/^https?:\/\//, "").replace(/\/$/, "");
}
